### ISSUE TITLE
rename broke shims

### ISSUE THREAD

**Issue by deregtd** [jdx/mise#1342]
**Describe the bug**
When upgrading from rtx to mise, on first run of activate, it detected the "migration" and moved the shims from ~/.local/share/rtx/shims to ~/.local/share/mise/shims, but didn't actually update the symlinks.  As such, the user must manually force a `mise reshim`.  This was tested on 2024.1.2 but does not appear to be addressed in the commits from 2024.1.3.

**To Reproduce**
Install rtx and activate your shell.  Upgrade to mise and then activate your shell.  Then try to use any shimmed tool (I used "go").  You'll get command not found, because it's still pointing at:

```
lrwxr-xr-x   1 user  staff   21 Dec 21 20:35 corepack -> /opt/homebrew/bin/rtx
```

After running `mise reshim` you get them fixed properly:

```
lrwxr-xr-x   1 user  staff   22 Jan  3 15:44 corepack -> /opt/homebrew/bin/mise
```

**Comment by jdx** [comment]
ah yeah good point. It was changed slightly to not move the shims directory but the result is the same: you'll need to manually run `mise reshim`. I'll try to think of a way to automate that.

**Comment by jdx** [comment]
I can't really think of a good way to do this unfortunately. The migration stuff can't really do it because if I call `mise reshim` there it would end up in an infinite loop. I could set an env var or something to prevent it but I think the logic would get a bit complex. I think it's probably best to just put this into the migration docs and leave it at that.

**Comment by jdx** [comment]
`mise reshim` runs the migrator, that's the problem

**Comment by deregtd** [comment]
ah i see.  if there's not a good way to separate out the "second part" of reshim to re-run, then you're prolly kinda hosed there.

**Comment by jdx** [comment]
it's certainly possible, like I could just not run the migration if we're doing a reshim but I don't want to overcomplicate the migrator since it runs every single time the CLI is launched. If I make it complicated, it's more likely to have a bug, and a bug might make the CLI not start at all so you wouldn't be able to even run `mise self-update`.
