### ISSUE TITLE
Confusing warning about settings in ~/.config/mise/config.toml

### ISSUE THREAD

**Issue by fvsch** [jdx/mise#1403]
Edit: looks like the main issue here is already fixed in `2024.1.12`. This report also has a short discussion of settings in `~/.config/mise/settings.toml` being silently ignored if they use a `[settings]` table header.

----

I think I moved my `~/.config/rtx/config.toml` to `~/.config/mise/config.toml` recently.

This file had the following content:

```toml
[settings]
experimental = true
```

With mise 2024.1.10 and 2024.1.12 I’m getting this warning printed at the start of the shell session:

```
mise [settings] inside of ~/.config/mise/config.toml is deprecated. A separate ~/.config/mise/config.toml file should be used instead.
mise Removing the [settings] section from ~/.config/mise/config.toml will remove this warning
```

Note how it's telling me to use a separate `~/.config/mise/config.toml` file, which is the exact same file path.

This got me confused and I guessed that maybe the `[settings]` header had to be removed (I was not super familiar with [TOML syntax](https://toml.io/en/v1.0.0), but apparently these are called table headers, and the header + key-value pairs it applies to are called a table, with “hash table” and “dictionary” given as synonyms, but not a section). So I changed the file contents to:

```toml
experimental = true
```

Which then triggered this error:

```
Error:   × error parsing config file: ~/.config/mise/config.toml
  ╰─▶ unknown key: experimental
```

My guess at this point is that the original warning is wrong, and should have said:

```diff
- A separate ~/.config/mise/config.toml file should be used instead.
+ A separate ~/.config/mise/settings.toml file should be used instead.
```

As a side note, if I create a `~/.config/mise/settings.toml` without a table header or with a `[settings]` table header, I’m not getting a warning or validation error either way.

After testing with `mise settings ls`, it looks like the version with a `[settings]` table header results in the settings being ignored. Should that be a warning? If manual migration results in users having a `settings.toml` file with a `[settings]` table header, it will fail silently.

**Comment by fvsch** [comment]
I saw the same warning (without the fix) after updating to `2024.1.12`, but it looks like that was because it was still in the same shell session, and the code responsible for the warning is loaded once at the start of the session (at least with Fish), so I was still seeing the warning from version `2024.1.10`.

I can confirm that the warning is correct in `2024.1.12` in a new terminal session.

**Comment by fvsch** [comment]
Thanks for the heads up @rdonkin.

**Comment by jdx** [comment]
for some explanation of why this was done (since I doubt it's obvious), I needed to separate the `[settings]` block out of the config files.

Before, you could have a `[settings]` section inside of any config file. This was problematic because some of the settings actually affect how config files themselves—and which config files—get loaded. This made the code for loading everything quite complex and some settings were actually impossible to even use in some places.

Changing this logic so there is just one global settings file makes things far more consistent. It's also going to make it possible for me to integrate mise with this [other project](https://github.com/jdx/usage) I'm in the middle of getting ready for an alpha launch of that will bring some features I really like.

You are correct that you don't need the `[settings]` header. I'll see if I can add that validation so it properly fails on invalid keys.

**Comment by jdx** [comment]
I considered automating this migration and creating the settings.toml on the user's behalf with the contents of config.toml. I decided against it because it would be complicated enough that it having a bug or 2 wouldn't be surprising. I also thought people might have config.toml as a symlink in a dotfiles repo but creating settings.toml might not also get added which could caue some confusion.
