### ISSUE TITLE
read from .config/mise/conf.d/* (fragmented configs)

### ISSUE THREAD

**Issue by jdx** [jdx/mise#1444]
@pepicrft mentioned he might be getting to a point where .mise.toml configs are getting large and could be split into separate files. I suspect this may be due to tasks.

What could be done? One idea is `.mise/*.toml` could all be config files, but I think that wouldn't work with the [profiles](https://mise.jdx.dev/profiles.html) feature.

For tasks specifically, maybe it might be possible to put them into a directory like `.mise/tasks/build.toml` where "build:*" tasks can live. On that note though, that directory should be configurable and I kind of think that "tasks" right in the repo root is better as default.

**Comment by jdx** [comment]
actually I think the solution is obvious: just read from a `.config/mise/conf.d` directory. that's the unix way to do it.

**Comment by pepicrft** [comment]
> actually I think the solution is obvious: just read from a .config/mise/conf.d directory. that's the unix way to do it.

What would the directory contain?

I'd wait to see the use cases users present us with. Otherwise, we might end up prematurely designing very bespoke solutions. This reminds me of my time working on the Shopify CLI. Internal developers asked for "workspaces" every single week. And every time I asked why? Their answer sounded very cargo-cutting: well.. because Yarn does it too, we should do it because developers are used to it.

**Comment by toupeira** [comment]
This proposal would solve my use case in https://github.com/jdx/mise/issues/1837, if it supported merging `[tools]` sections. Then I could have a second configuration file with development tools, and symlink that only on machines I use for development. I would even prefer this approach vs. global profiles, since I wouldn't have to set `MISE_ENV` too.

As for what the directory would contain, I guess simply any number of `.toml` files, which would be merged in alphanumeric order?

Not sure how this would work in combination with profiles. One suggestion: Instead of using `conf.d`, you could have a `config.toml.d`, `config.production.toml.d` etc., which would be read (and merged) in addition to (or instead of) any main configuration file?

**Comment by lokkju** [comment]
This would be a huge help for managing ansible deployment of mise; currently, ensuring the default mise config contains some configuration blocks is something of a pain.
