### ISSUE TITLE
[Documentation] Add instruction example to Automatic Virtualenv Activation page 

### ISSUE THREAD

**Issue by swirle13** [jdx/mise#1580]
Looking at the instructions page for how to set [automatic virtualenv activation](https://mise.jdx.dev/lang/python.html#automatic-virtualenv-activation), there is no indication that this can be achieved via cli. I only happened to stumble upon setting this when working on my own guide. I received the following output when adding a yet-uncreated virtualenv to `.mise.toml`:

```bash
mise please enable experimental mode with `mise settings set experimental true` to use python virtualenv activation                                                                                                                            
mise no venv found at: /path/to/nonexistent/venv

To have mise automatically create virtualenvs, run:
mise settings set python_venv_auto_create true

To create a virtualenv manually, run:
python -m venv /path/to/nonexistent/venv
```

Can this line be included in the documentation to help users know/learn this can be done in addition to setting `MISE_PYTHON_VENV_AUTO_CREATE` to `true`?

I also cannot find a way to set the `virtualenv` value in `.mise.toml` via cli. A command to set this would be really useful. Something like:

```
mise use python@3.10 virtualenv="relative/or/absolute/path"  # valid virtualenv values as indicated in the docs
```

My current process for some onboarding docs are to have users copy/paste the following ugly code:

```bash
cat <<EOF > .mise.toml  
[tools]
poetry = {version='latest', pyproject='pyproject.toml'}
python = {version='3.8', virtualenv='.venv'}
EOF
```

**Comment by jdx** [comment]
there are other threads/discussions about this so I won't belabor the point.

What I will say is that I'm trying to move away from automatically activating the venv. Whether it would ever actually be deprecated is a bit unclear. What it needs is a real owner that understands python and that's not me.

Also, the configuration here is going to move from being under `[tools]` to being under `[env]`—I don't have a timeline for that (or anything in mise) but it's a relatively near-term plan.

I should point out this is and has always been experimental functionality too.

Anyhow, I'm going to close because the last thing I want right now is more people adopting this right before it changes significantly. Once there are some replacements in place there will be documentation around it. I'm not even going to think about CLI commands right now—there's too much else to focus on.

btw don't interpret this negatively, this is important functionality, it just needs to find a place in mise that fits where it can be properly maintained for the long haul. What we have currently is not that.
