### ISSUE TITLE
golang: support patch versions in go.mod

### ISSUE THREAD

**Issue by grosser** [jdx/mise#1689]
```
# go.mod
go 1.21.4
```

then
```
cd .
o version
bash: command not found: go
```

works fine if .go-version is added

**Comment by jdx** [comment]
this was intentionally left out to avoid issues such as https://github.com/asdf-community/asdf-golang/issues/99

**Comment by grosser** [comment]
the issue is about 1.20 not saying what the patch version is, but the new `go 1.21.4` supplies the full version

mise supplies `1.21` / `1` when installing 1.21.4 so afaik it would make sense to support even `go 1.21` syntax

if you disagree then what about making this opt-in ?

**Comment by jdx** [comment]
mise doesn't read go.mod at all so I'm not really clear on what you're talking about patch versions here

**Comment by grosser** [comment]
the linked issue https://github.com/asdf-community/asdf-golang/issues/99 was about not supporting go.mod because it does not have a fully defined version (i.e. `go 1.21` and not `go 1.21.4`)

I'm proposing to read that file as fallback to `.go-version` and use it's version if it's a full version `go 1.21.4` for example

**Comment by jdx** [comment]
the issue is that the field isn't "deterministic" which it arguably could be in mise because of fuzzy matching but we would have to answer the question of what the determinism should be. My reading of the go docs is that this field is for defining the _minimum_ supported version, not the minor version of the toolchain. If all the field defines is "latest" there isn't any value in supporting it.

This seems similar to the engines field in node where you should only bump it when you want to remove support for particular versions not for defining which version of node to actually use. We don't use this field for node for the same reason.

I suspect this is the reason the go designers added toolchain as a separate field. One is for the expected version and the other is for defining compatibility.

I don't think we should be using go.mod, it sounds like the asdf-golang maintainers don't either and I suspect the go designers also feel this way. I don't even think this should be the option since to me it's promoting an actively harmful pattern. If it were me I would just add a .go-version file but if you really want this you could just use asdf-golang which has that capability.

**Comment by grosser** [comment]
I mostly want it so I don't have to add .go-version to every go repo
since I usually match that to the go.mod / dockerfile / ci setup ... since that "minimum version" is not really something reliable :)

an alternative could be to pick a version that is >= than what the go.mod says, not really what I need but could be a nice usability feature

atm it's kinda rough because you cd into a go project and there is no `go` available

**Comment by jdx** [comment]
Why not just set go@latest globally?

**Comment by grosser** [comment]
hehe true that would work too :)

**Comment by grosser** [comment]
newer go versions tend to break older go code, so latest is not a great option
I saw goenv has GOENV_GOMOD_VERSION_ENABLE for this, would that be ok ?
(as in: MIISE_GOMOD_VERSION_ENABLE=true -> read the version from go.mod)
