### ISSUE TITLE
Apple x64 version of mise doesn't work.

### ISSUE THREAD

**Issue by itsmo1031** [jdx/mise#1797]
**Describe the bug**
Hello! First of all, thank you for your amazing work. 

<img width="972" alt="image" src="https://github.com/jdx/mise/assets/34124582/699e4212-903f-4f91-993c-312e82484e10">

I tried to install mise-x64 for use node 14 in M1 Mac, but when I tried to execute `mise-x64 --version` after downloading it, it took forever and didn't let me know its version. `mise-x64 doctor` didn't work either.

**To Reproduce**
Just follow this tip in [your official document](https://mise.jdx.dev/tips-and-tricks.html#macos-rosetta) in M1 Mac(2020, Sonoma 14.3).

```shell
mkdir -p ~/.local/bin
curl https://mise.jdx.dev/mise-latest-macos-x64 > ~/.local/bin/mise-x64
chmod +x ~/.local/bin/mise-x64
~/.local/bin/mise-x64 --version
mise 2024.x.x
```

Please let me know if further information is needed. Thanks!

**Comment by roele** [comment]
If you want to use non-ARM builds of any sort you can also install those manually by extracting them to `~./local/share/mise/installs/<plugin>/<version>` and clearing the cache with `mise cache clear`. The runtime should show up normally with `mise ls` after that. These will then run via Rosetta emulation.

With Node you might run into further issues due to Python 2 not available anymore on MacOS and the such but that is another topic for another day...

**Comment by zachsvanhandel** [comment]
I ran into a similar issue when trying to install an older version of Node on an M1 MacBook.

Initially I saw the following error message after following the steps outlined in the [macOS Rosetta guide](https://mise.jdx.dev/tips-and-tricks.html#macos-rosetta).
```console
$ ~/.local/bin/mise-x64
mise mise-x64 is not a valid shim
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

After setting `MISE_VERBOSE=1`, the output indicated that the error location was [src/shims.rc:231](https://github.com/jdx/mise/blob/96ad08d8acb6b7a4eff0be2f49022080d10b9b71/src/shims.rs#L231). Because I was curious and wanted to get it working, I looked into the git history for the file and noticed that a recent commit (https://github.com/jdx/mise/commit/fae51a7ef38890fbf3f864957e0c0c6f1be0cf65) is likely the culprit as the change does not allow the binary to be named `mise-x64`. I tried renaming the binary to `mise` and it worked! Note that I initially installed mise via Homebrew, so the macOS arm64 binary was located at `/opt/homebrew/bin/mise` (_**not**_ `~/.local/bin/mise`). If you installed the macOS arm64 binary to that location, make sure you do not overwrite it by renaming the macOS x64 binary.
```console
$ mv ~/.local/bin/mise-x64 ~/.local/bin/mise
$ ~/.local/bin/mise --version
2024.3.7 macos-x64 (3bde772 2024-03-21)
```

As far as the behavior @itsmo1031 was seeing, I saw similar behavior when I tried adding `~/.local/bin` to `PATH` (before I renamed the binary from `mise-x64` to `mise`). It seemed to get stuck in an infinite loop based on the debug output I saw while running with the verbose option enabled.
```console
$ export PATH=$PATH:~/.local/bin
$ mise-x64
...
```

I tried adding `~/.local/bin` to `PATH` again after renaming the binary from `mise-x64` to `mise` and it seems to be working as expected now, so I'm assuming the original error I saw may be causing that unexpected behavior too...

Hopefully this information helps! I just started using mise last week while setting up my development environment on a new MacBook. Besides this minor issue, it's been perfect 😄

**Comment by itsmo1031** [comment]
> I ran into a similar issue when trying to install an older version of Node on an M1 MacBook.
> 
> Initially I saw the following error message after following the steps outlined in the [macOS Rosetta guide](https://mise.jdx.dev/tips-and-tricks.html#macos-rosetta).
> 
> ```
> $ ~/.local/bin/mise-x64
> mise mise-x64 is not a valid shim
> mise Run with --verbose or MISE_VERBOSE=1 for more information
> ```
> 
> After setting `MISE_VERBOSE=1`, the output indicated that the error location was [src/shims.rc:231](https://github.com/jdx/mise/blob/96ad08d8acb6b7a4eff0be2f49022080d10b9b71/src/shims.rs#L231). Because I was curious and wanted to get it working, I looked into the git history for the file and noticed that a recent commit ([fae51a7](https://github.com/jdx/mise/commit/fae51a7ef38890fbf3f864957e0c0c6f1be0cf65)) is likely the culprit as the change does not allow the binary to be named `mise-x64`. I tried renaming the binary to `mise` and it worked! Note that I initially installed mise via Homebrew, so the macOS arm64 binary was located at `/opt/homebrew/bin/mise` (_**not**_ `~/.local/bin/mise`). If you installed the macOS arm64 binary to that location, make sure you do not overwrite it by renaming the macOS x64 binary.
> 
> ```
> $ mv ~/.local/bin/mise-x64 ~/.local/bin/mise
> $ ~/.local/bin/mise --version
> 2024.3.7 macos-x64 (3bde772 2024-03-21)
> ```
> 
> As far as the behavior @itsmo1031 was seeing, I saw similar behavior when I tried adding `~/.local/bin` to `PATH` (before I renamed the binary from `mise-x64` to `mise`). It seemed to get stuck in an infinite loop based on the debug output I saw while running with the verbose option enabled.
> 
> ```
> $ export PATH=$PATH:~/.local/bin
> $ mise-x64
> ...
> ```
> 
> I tried adding `~/.local/bin` to `PATH` again after renaming the binary from `mise-x64` to `mise` and it seems to be working as expected now, so I'm assuming the original error I saw may be causing that unexpected behavior too...
> 
> Hopefully this information helps! I just started using mise last week while setting up my development environment on a new MacBook. Besides this minor issue, it's been perfect 😄

You're my lifesaver @zachsvanhandel !! It worked perfectly normally when I renamed `mise-x64` to `mise`! I never dared think that something like this would happen because of the name🤣.

**Comment by roele** [comment]
Thanks @zachsvanhandel for the analysis. I guess allowing suffixes makes sense since this also enables a development use-case i have using a symlink from `mise-debug` to the build target for local experiments.
