### ISSUE TITLE
Someway to decrease build time?

### ISSUE THREAD

**Issue by M1kep** [jdx/mise#1834]
When installing on Arch Linux via `yay`, the build time is ~4 minutes.

Is there some way to provide builds for this to the AUR setup, or decrease build times?

I realize 4 minutes isn't _that_ much, but it's consistently 4-5x as long as the rest of the system update process.

**Comment by suicide** [comment]
Memory usage also seemed to have exploded over the past releases. I am running an older secondary arch system with only 4gb of ram and when trying to compile, the entire system freezes. I didn't have the time to investigate further but using the `mise-bin` package obviously helped by avoiding compiling

**Comment by jdx** [comment]
yeah if possible using binary packages is better. You can also try changing settings like lto. I'd accept a PR for a new profile like "fast-release" or something that we could use for things like AUR.

**Comment by kevindetry** [comment]
Switching to thin LTO helps to speed up the build process quite a lot indeed: on my machine instead of 1m17s it becomes 20s. Disabling LTO completely doesn't make it any quicker though.

I wonder, how much worse the performance is with thin LTO instead of fat? So far I noticed that the binary is 4M smaller with fat LTO.

**Comment by jdx** [comment]
lto is now disabled by default
