### ISSUE TITLE
Pass task args to tasks in depends

### ISSUE THREAD

**Issue by rgeraskin** [jdx/mise#1959]
We can pass arg to task like `mise run build arg1`. But if `build` task depends on, for example, `lint` task, `lint` task will not get `arg1 ` as arg. It's very handy to have this feature imo.

**Comment by jdx** [comment]
I don't understand how this could work in a useful way. Maybe you could show me an example.

**Comment by roman-geraskin-m10** [comment]
it's usefull for the tasks that require args. Like

```
# .mise.toml

[settings]
experimental = true

[tasks.pull]
run = "docker pull"

[tasks.run]
depends = ["pull"]
run = "docker run --rm"
```

Run:
```
❯ mise r run ubuntu
[pull] $ docker pull
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Download an image from a registry
mise [pull] exited with code 1
```

But an invocation of pull directly works:
```
❯ mise r pull ubuntu
[pull] $ docker pull
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:562456a05a0dbd62a671c1854868862a4687bf979a96d48ae8e766642cd911e8
Status: Image is up to date for ubuntu:latest
docker.io/library/ubuntu:latest
```

**Comment by rgeraskin** [comment]
it's usefull for the tasks that require args. Like

```
# .mise.toml

[settings]
experimental = true

[tasks.pull]
run = "docker pull"

[tasks.run]
depends = ["pull"]
run = "docker run --rm"
```

Run:
```
❯ mise r run ubuntu
[pull] $ docker pull
"docker pull" requires exactly 1 argument.
See 'docker pull --help'.

Usage:  docker pull [OPTIONS] NAME[:TAG|@DIGEST]

Download an image from a registry
mise [pull] exited with code 1
```

But an invocation of pull directly works:
```
❯ mise r pull ubuntu
[pull] $ docker pull
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:562456a05a0dbd62a671c1854868862a4687bf979a96d48ae8e766642cd911e8
Status: Image is up to date for ubuntu:latest
docker.io/library/ubuntu:latest
```

**Comment by jdx** [comment]
OK but the second you add an extra dependency to either of these you're sending `ubuntu` to something that probably shouldn't receive that.

**Comment by roman-geraskin-m10** [comment]
You are right. Maybe it's better to add a new option for task to be able to inherit args?

**Comment by rgeraskin** [comment]
You are right. Maybe it's better to add a new option for task to be able to inherit args?

**Comment by jdx** [comment]
I think you should just use an environment variable like `DOCKER=ubuntu`.

**Comment by rgeraskin** [comment]
It's ok to use env variable for single arg. But it's not handy to do it with a changeble number of args =(

I've added `-q` arg:
`mise r run -q ubuntu`

**Comment by jdx** [comment]
You're not thinking this through. The second you want to run any param that isn't supported by `docker build` this would break: `mise r run -q ubuntu -w $PWD` for example. This might work in a handful of contrived use-cases but that's it.

**Comment by jdx** [comment]
I will say though that I plan to make the arg functionality in mise tasks vastly more comprehensive in the future and supporting global args is something I'm thinking about.

**Comment by jdx** [comment]
Also, not that you can do anything about this, I've always felt that docker is a poorly designed CLI and this is a good example. It blows my mind there still isn't (to my knowledge) a simple `docker build-and-run` command.

**Comment by rgeraskin** [comment]
yes, and imo it's a responsibility for a mise-user to decide how to set task dependencies. So additional switchers are a way to go.

```
[tasks.pull]
run = "docker pull"
inherit_args = true
```
or
```
[tasks.run]
depends = ["pull"]
run = "docker run —rm"
propagate_args = true
```

I agree with you about the cli design of docker. But docker is just an example, i'm actually trying to use tasks for terraform cli. But examples with terraform more complicated to show 🙂

**Comment by rgeraskin** [comment]
Another idea: just propagate shell args like $1, $2, $@ and so on to the depends task. Because $1 and $2 are accessible only in task that have been called directly from command line for now.

Actually, it provides more opportunities to user to compose run commands with args. And also it's optional to use $1 or $2 in a task.

```
# .mise.toml

[settings]
experimental = true

[tasks.pull]
run = """
#/bin/bash
docker pull $1
"""

[tasks.run]
depends = ["pull"]
run = """
#/bin/bash
docker run —rm $1
"""
```

**Comment by jdx** [comment]
Yeah I like that idea. It'll need to wait until task args get overhauled using my work on usage though. It may end up looking differently though, I may take advantage of templates so you could do it like this:

```toml
[tasks.pull]
run = """
#/bin/bash
docker pull {{ args.0 }}
"""
```

reason being is you could make it work like this alternatively:

```toml
[tasks.pull]
run = """
#/bin/bash
docker pull {{ options["docker-image"] }}
"""
```

which would be called with `mise r run --docker-image=ubuntu`

**Comment by rgeraskin** [comment]
Excited to see your updates on task arguments! Thanks in advance for your work)

**Comment by eglimi** [comment]
This would be a useful feature I'm also looking forward to.

Maybe [just](https://github.com/casey/just?tab=readme-ov-file#recipe-parameters) can be used as additional inspiration for some aspects. E.g. I like it's explicit argument handling in recipes. E.g.

```
test target tests="all": (build target)
  ./test --tests {{tests}} {{target}}
```

This is nice because recipes explicitly define what input they expect and fail otherwise, giving the user a hint how to use it.

**Comment by boris-smidt-klarrio** [comment]
Could it be a solution to do something like this now that we have template args?

```
[tasks."test"]
depends = [
    'build {{arg(name="test-name")}}',
    'pre-test {{arg(name="test-name")}}',
]
run = "test {{arg(name="test-name")}}"
```

Or would this become too complicated to keep track of which tasks to run?

The advantage of this would be that you could do

```mise run test --test-name=my-slow-test ::: test --test-name=my-other-slow-test```
Not sure how else i would have to implement such a thing?

**Comment by jdx** [comment]
I would just do this:

```toml
[tasks."test"]
depends = [
    'build {{arg(name="test-name")}}',
    'pre-test {{arg(name="test-name")}}',
]
run = """
test="{{arg(name="test-name")}}"
mise run build "$test" ::: pre-test "$test"
test "$test"
"""
```

**Comment by boris-smidt-klarrio** [comment]
I tried out a simple setup with tasks to see what the behavior difference is between hardcoding tasks and there dependencies vs running a mise task with a mise run in it.

To keep the case simple and stay within the limits of the current mise feature set only the leaf tasks have args, but in an ideal example the arg should be passed to one of the tasks to show that they should rerun.

```toml
[tasks."t1"]
run = "echo t1"

[tasks."t2"]
depends=[ "t1"]
run = "echo t2"
[tasks."t3"]
depends=[    "t1",    "t2"]

run = "echo t3"
[tasks."t4"]
depends=[    "t1",    "t2"]
run = "echo t4"

[tasks."test1"]
depends=[    "t4",    "t3"]
run = "echo test1"

[tasks."test2"]
depends=[    "t4",    "t3"]
run = "echo test2"

[tasks."test-with-arg"]
run = """
mise run t4 ::: t3
echo "{{arg(name="test")}}"
"""
```

So when we run `mise run t6 "test" ::: t6 "test2"` it will redo all dependent tasks twice.
The more args tasks we pass the more tasks are redone. This is also a 'race condition' case and can't really be solved since mise is unaware what tasks to run until it is running the tasks.
Also the color highlighting disappears for the sub mise runs.
It will also run more tasks in parallel then its task limit allows for since the are separate processes.

```bash 
mise run t6 "test" ::: t6 "test2"
[test-with-arg] $ mise run t4 ::: t3
[test-with-arg] $ mise run t4 ::: t3
[t1] $ echo t1
[t1] $ echo t1
[t1] t1
[t1] t1
[t2] $ echo t2
[t2] $ echo t2
[t2] t2
[t2] t2
[t4] $ echo t4
[t4] $ echo t4
[t3] $ echo t3
[t3] $ echo t3
[t4] t4
[t3] t3
[t3] t3
[t4] t4
[test-with-arg] test
[test-with-arg] test2
[test-with-arg] finished in 55.8ms
[test-with-arg] finished in 55.7ms
Finished in 69.0ms
```

Now when we hardcode the task args then mise can get a full task dependency graph and schedule the tasks only once avoiding race conditions and limits the tasks parallelism. Also all output is highlighted as expected.
```
mise run test1 ::: test2                        
[t1] $ echo t1 
[t1] t1
[t1] finished in 3.8ms
[t2] $ echo t2 
[t2] t2
[t2] finished in 2.6ms
[t4] $ echo t4 
[t4] t4
[t4] finished in 2.5ms
[t3] $ echo t3 
[t3] t3
[t3] finished in 2.3ms
[test1] $ echo test1 
[test2] $ echo test2 
[test1] test1
[test1] finished in 2.5ms
[test2] test2
[test2] finished in 2.9ms
Finished in 43.2ms
```

So mise tasks calling mise isn't ideal since they will be separate processes with different tasks contexts.
So either mise needs to be smart and add the new tasks to its own process context, as if it was a daemon, when `mise run` calls another `mise run`. I suspect this is how grade does it.

Or it could be made explicit and allow args to dependencies this allows mise to build the whole task graph and then schedule the execution. Tasks with an argument will be listed with the argument in the logging as they would also respect the task parallelism limit. 
````log
[t5 test-1] ran test-1
[t5 test-2] ran test-2
```
