### ISSUE TITLE
implement more tera functions

### ISSUE THREAD

**Issue by jdx** [jdx/mise#2049]
[just has quite a few functions](https://github.com/casey/just?tab=readme-ov-file#system-information) which is a good starting point for us to improve what can be done with templates in mise

**Comment by tfh-cri** [comment]
some equivalent to the tera built-in `slugify` would be useful (in my current need, adding a git-branch specific suffix to a python virtualenv managed by mise).

I assumed the tera builtin would already work, but looks like mise is using the 
```
tera = { ..., default-features = false }
```
definition which removes various functions including `slugify`.

A haphazard local rebuild suggests `default-features = true` adds about 3MB to the final binary (23->26MB), so might be excessive for just that function.

**Comment by jdx** [comment]
I'd accept a pr to add that feature for sure

**Comment by jdx** [comment]
in fact all the default ones seem like they could be useful

**Comment by erickguan** [comment]
I plan to implement this in 3 steps.

1. I will implement functions with "strict" definitions. They are;
  - system information
  - Environment Variables
  - Invocation Directory
  - Source and Source Directory
  - String Manipulation
  - Path Manipulation
  - UUID and Hash Generation
  - Semantic Versions
2. After that, we can discuss how to handle errors for other functions generating runtime failures and filesystem, shell access. I have not thought about security, etc.
3. Then the other functions you consider make sense. e.g. no point implementing `justfile`.

What do you think about it?

**Comment by jdx** [comment]
tera already supports some of this but for what it doesn't have support this sounds fine

**Comment by erickguan** [comment]
Now we have added most of `just` functions, at least within PRs. A quick question and some progress updates.

Do you want to improve error handling or it's a future improvment? You don't use `tera::Error` which generally provides a few more error information. The current way of throwing error via CLI is fine judging no one complains.

You mentioned `invocation_directory` and other paths in #2569. I saw some XDG paths in `env.rs` but not more than that. I will leave them to you.

Then the last few functions are:
- Error Reporting
- Random
- Datetime

I don't see a point implementing `just_exexcutable` nor `just_pid` functions. `is_dependency` is not relevant because mise is not a build system.

**Comment by jdx** [comment]
> Do you want to improve error handling

yeah, doesn't have to be a part of this issue necessarily though

> You mentioned invocation_directory and other paths in https://github.com/jdx/mise/pull/2569. I saw some XDG paths in env.rs but not more than that. I will leave them to you.

I added `cwd` and `config_root` which I think should suffice: https://mise.jdx.dev/templates.html

> I don't see a point implementing just_exexcutable nor just_pid functions.

I think these could be useful, especially `mise_executable`—probably on the context object as variables though not as functions. These should be available in env.rs somewhere.

I think we should still add support for absolute as well as the xdg path variables (xdg should just be on the context object). xdg should be easy, just add [these](https://github.com/jdx/mise/blob/main/src/env.rs#L34-L45) to the context object.
