### ISSUE TITLE
All backends should include their dependencies on PATH

### ISSUE THREAD

**Issue by bhollis** [jdx/mise#2260]
The Go backend includes `dependency_env`, which means that it should include any version of Go that's managed by mise on PATH when it runs commands: https://github.com/jdx/mise/blob/main/src/backend/go.rs#L77

Other backends don't do this. e.g. npm: https://github.com/jdx/mise/blob/main/src/backend/npm.rs#L71-L72. This means that the npm backend can't install unless `npm` is already on `PATH`.

All of the backends already declare dependencies (e.g. https://github.com/jdx/mise/blob/main/src/backend/pipx.rs#L33-L35) in order to install them before running the backend, so it makes sense that they should all make use of them while running the backend.

**Comment by jdx** [comment]
mise does do this, but experimental backends are still a work in progress so there are gaps

**Comment by liskin** [comment]
I believe these two fixes merged recently are related to the issue:
* https://github.com/jdx/mise/pull/2524
* https://github.com/jdx/mise/pull/2532

Unfortunately, mise still won't install `cargo-binstall` in time for it to be used for `cargo:…` tools because it's not declared as a dependency in https://github.com/jdx/mise/blob/d161afe843694020f22fc981537f81e5ea7f2896/src/backend/cargo.rs#L35

**Comment by liskin** [comment]
Actually, doesn't seem to work for pipx/uv either, despite the dependencies being declared
https://github.com/jdx/mise/blob/bc4fae3f1acefdf0fb05f8b97a0ec1703a216f57/src/backend/pipx.rs#L33-L35

```console
$ mise uninstall pipx:timezonefinder
$ mise uninstall ubi:astral-sh/uv
$ MISE_VERBOSE=1 mise install
[DEBUG] ARGS: mise install
[DEBUG] Config {
    Config Files: [
        "~/.mise.toml",
        "~/.config/mise/config.toml",
    ],
}
[DEBUG] ToolRequestSet.build(132.668µs): ToolRequestSet: cargo:ast-grep@0.27.1 cargo:cargo-audit@0.20.1 cargo:cargo-cache@0.8.3 cargo:cargo-edit@0.12.3 cargo:cargo-watch@8.5.2 cargo:ripgrep_all@0.10.6 cargo:tokio-console@0.1.12 cargo:watchexec-cli@2.1.2 ubi:YodaEmbedding/frece@v1.0.6 ubi:cargo-bins/cargo-binstall@v1.10.5 usage@0.3.1 ubi:astral-sh/uv@0.4.10 pipx:timezonefinder@6.5.2

[DEBUG] install_versions: ubi:astral-sh/uv@0.4.10 pipx:timezonefinder@6.5.2
[DEBUG] $ ubi --in /home/tomi/.local/share/mise/installs/ubi-astral-sh-uv/0.4.10/bin --project astral-sh/uv --tag 0.4.10
[DEBUG] $ uv tool install timezonefinder==6.5.2
mise ubi:astral-sh/uv@0.4.10 ✓ installed
Error: 
   0: failed to execute command: uv tool install timezonefinder==6.5.2
   1: No such file or directory (os error 2)

Location:
   src/cmd.rs:253

Version:
   2024.9.3 linux-x64 (e0d1317 2024-09-12)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I had to manually `mise reshim` and invoke `mise install` for the second time for it to pick up `uv`.

**Comment by jdx** [comment]
Right now it doesn't work with full names `ubi:astral-sh/uv` instead of `uv` unless we explicitly added those as dependencies. I think what we could do is modify the dependency lookup to explode the possible dependencies into any matching the full names (it doesn't do this now).

In other words, if the registry had the following:

```toml
uv = ["ubi:astral-sh/uv", "asdf:asdf-community/asdf-uv"]
```

then it would use `uv`, `ubi:astral-sh/uv`, or `asdf:asdf-community/asdf-uv` as dependencies if any of those are active tools.
