### ISSUE TITLE
Install from cargo backend using `--git`

### ISSUE THREAD

**Issue by pd93** [jdx/mise#2420]
For one reason or another, some Rust projects are not published on crates.io. For example, [zenith](https://github.com/bvaisvil/zenith) does not have a crate. Instead, they ask their users to install via `--git` flag. I could not see any way to specify this using Mise.

It would be nice to be able to specify this as an option in the config file. Or better yet, support a similar syntax to the Go backend where it would just install using `--git` if it detects a path instead of a package name.

**Comment by jdx** [comment]
we would do this via `ref:` syntax—though admittedly the work around that is only partially complete. The gaps are around updating. That said, it's really strange to me that a rust cli _wouldn't_ be distributed via crates. I don't think I've ever seen that before.

**Comment by halostatue** [comment]
I’ve seen it a few times (and there's times that you need to clone a repository with a Go cli tool, which is even weirder), especially when there's a crate that has the desired name of the tool (https://crates.io/search?q=zenith for this one shows both an exact match and at least one other match that would be desirable, although `zenith-top` and `zenith-cli` are both available). I also think that in some cases, the preference is either to (a) go through GitHub releases or (b) keep it installable via `--git` because they're not yet ready for casual users to adopt the tool.

**Comment by pd93** [comment]
> it's really strange to me that a rust cli wouldn't be distributed via crates

The reasons for this were discussed in [this issue](https://github.com/bvaisvil/zenith/issues/5). My understanding is that a forked dependency meant that it couldn't be easily published. I'm not hugely experienced with Rust, so forgive my ignorance on the topic.

It actually seems like the PR in question has since been merged, so I'm not sure if this is still a blocker. However the package is still only installable with the `--git` flag if using Cargo. Not sure if this is a common problem and I agree the best fix would be for the author to publish a package, but in lieu of this, it would be a useful feature for mise to support provided the implementation isn't too difficult.

> there's a crate that has the desired name of the tool

This is actually how I ran into the issue in the first place. I attempted to add "cargo:zenith" to my config without checking crates.io (stupidly) and got some very unexpected output.
