### ISSUE TITLE
pipx: support features

### ISSUE THREAD

**Issue by curio77** [jdx/mise#2491]
pipx has a concept of optional features upon package installation, via `pipx install package[feature,…]`.  This is used, for example, by [Harlequin](https://harlequin.sh/docs/getting-started).

To my knowledge, mise has no support for this.  Would it be possible to add it?

As a work-around, for the example of Harlequin, one can install things via `pip install harlequin parlequin-postgress` etc. instead.

**Comment by joshbode** [comment]
It would be nice to support the `--preinstall` option also, which allows you to inject additional packages to the environment that aren't explicitly covered by a declared extra. Note: this option can be specified multiple times, also.
This is equivalent to running `pipx inject some-tool some-package` on an existing tool, but nicer since it does it at install-time.
