### ISSUE TITLE
Add support for uvx backend

### ISSUE THREAD

**Issue by antoniomdk** [jdx/mise#2506]
[uvx](https://docs.astral.sh/uv/concepts/tools/) is a  `pipx` replacement built in Rust (on top of `uv`). I think for people using `uv` as the package manager, it makes sense to also use `uvx` for tools.

I can contribute to this feature, but I may need some guidance on best practices for this use case. I think the implementation would be pretty similar to the `pipx` backend, so I am not sure if adding a new backend is recommended, or maybe we can extend the `pipx` module.

**Comment by jdx** [comment]
I think we can do something like what we've done with cargo/cargo-binstall. Should be pretty easy but make sure we have a setting to opt out of this.

**Comment by jdx** [comment]
https://github.com/jdx/mise/blob/main/docs/contributing.md#adding-a-new-setting

**Comment by jdx** [comment]
I imagine you wouldn't have trouble finding the cargo-binstall code, but here it is just in case. uvx should be something similar: https://github.com/jdx/mise/blob/ba90c3bbe71bd33d628df607326da9f0cf363af1/src/backend/cargo.rs#L82-L90

One use-case to consider though is when people have uv itself installed via mise. In the ubi backend we handle that like this: https://github.com/jdx/mise/blob/ba90c3bbe71bd33d628df607326da9f0cf363af1/src/backend/ubi.rs#L31

It might be as simple as adding `uv` as a dependency. That doesn't mean that mise will automatically install the uv binary via mise if using the pipx backend, just that if uv is _already_ a dependency it will be loaded first so that `uv` will be on PATH. In theory at least, admittedly that part of the code is new and has rough edges.

**Comment by antoniomdk** [comment]
@jdx Thanks a lot for the info, it was really helpful. I've started to work on this [PR](https://github.com/jdx/mise/pull/2509).
