### ISSUE TITLE
`_.python.venv` does not correctly prepend the venv path if a virtualenv is active (fish shell)

### ISSUE THREAD

**Issue by albireox** [jdx/mise#2718]
**Describe the bug**

When one already has a virtualenv active, a `.mise.toml` file with a `_.python.venv` directive will add the commanded venv to PATH but always after the already active one. For example if I have a `$PATH` like

```text
/Users/gallegoj/.local/share/virtualenv/gallegoj/bin /Users/gallegoj/.cargo/bin /usr/local/bin /Users/gallegoj/.local/bin /usr/bin /bin
```

where `/Users/gallegoj/.local/share/virtualenv/gallegoj/bin` is an activated environment, and `cd` to a directory with a `.mise.toml`

```toml
[env]
_.python.venv = ".venv"
```

the resulting `$PATH` will be

```text
/Users/gallegoj/.local/share/virtualenv/gallegoj/bin /Users/gallegoj/Documents/Code/sdss5/sdss-sep/.venv/bin /Users/gallegoj/.cargo/bin /usr/local/bin /Users/gallegoj/.local/bin /usr/bin /bin
```

instead of the expected

```text
/Users/gallegoj/Documents/Code/sdss5/sdss-sep/.venv/bin /Users/gallegoj/.local/share/virtualenv/gallegoj/bin /Users/gallegoj/.cargo/bin /usr/local/bin /Users/gallegoj/.local/bin /usr/bin /bin
```

I've only tested this in `fish`.

**`mise doctor` output**

```text
version: 2024.10.1 macos-x64 (7184e60 2024-10-07)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-apple-darwin
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 7 Oct 2024 19:08:40 +0000
  Rust Version: rustc 1.81.0 (eeb90cda1 2024-09-04)
  Profile: release

shell:
  /usr/local/bin/fish
  fish, version 3.7.1-2332-g4c43819d3

dirs:
  data: ~/.local/share/mise
  config: ~/.config/mise
  cache: ~/Library/Caches/mise
  state: ~/.local/state/mise
  shims: ~/.local/share/mise/shims

config_files:
  ~/Documents/Code/sdss5/sdss-sep/.python-version
  ~/Documents/Code/sdss5/sdss-sep/.mise.toml

backends:
  cargo
  core
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  python@sdss-sep  (missing)

env_vars:
  MISE_SHELL=fish

settings:
  activate_aggressive = false
  all_compile = false
  always_keep_download = false
  always_keep_install = false
  asdf = true
  asdf_compat = false
  cache_prune_age = "30d"
  cargo_binstall = true
  ci = false
  color = true
  debug = false
  disable_default_shorthands = false
  disable_hints = []
  disable_tools = []
  experimental = false
  go_default_packages_file = "~/.default-go-packages"
  go_download_mirror = "https://dl.google.com/go"
  go_repo = "https://github.com/golang/go"
  go_set_gopath = false
  go_set_goroot = true
  go_skip_checksum = false
  http_timeout = 30
  jobs = 4
  legacy_version_file = true
  legacy_version_file_disable_tools = []
  libgit2 = true
  log_level = "info"
  not_found_auto_install = true
  paranoid = false
  pin = false
  pipx_uvx = false
  plugin_autoupdate_last_check_duration = "7d"
  python_default_packages_file = "~/.default-python-packages"
  python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
  python_venv_auto_create = false
  quiet = false
  raw = false
  trace = false
  trusted_config_paths = []
  use_versions_host = true
  verbose = false
  vfox = false
  yes = false

  [node]

  [ruby]
  default_packages_file = "~/.default-gems"
  ruby_build_repo = "https://github.com/rbenv/ruby-build.git"
  ruby_install = false
  ruby_install_repo = "https://github.com/postmodern/ruby-install.git"

  [status]
  missing_tools = "if_other_versions_installed"
  show_env = false
  show_tools = false
No warnings found
No problems found
```

**Comment by hxii** [comment]
Seconding this issue:
```
Paul_Glushak@Paul ~> pwd
/Users/Paul_Glushak
Paul_Glushak@Paul ~> echo $PATH | sed 's/ /\n/g'
/Users/Paul_Glushak/dev/forter-dev-cli/.venv/bin
/Users/Paul_Glushak/.local/share/mise/installs/pipx/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/python/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/poetry/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/usage/latest/bin
/Users/Paul_Glushak/.local/bin
/opt/homebrew/bin
...
```
Then `cd` somewhere else
```
Paul_Glushak@Paul ~> z boku
Paul_Glushak@Paul ~/d/boku (main)> cat .mise.toml
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: .mise.toml
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [tools]
   2   │ python = "latest"
   3   │
   4   │ [env]
   5   │ _.python.venv = { path = ".venv", create = true }
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Paul_Glushak@Paul ~/d/boku (main)> echo $PATH | sed 's/ /\n/g'
/Users/Paul_Glushak/dev/forter-dev-cli/.venv/bin
/Users/Paul_Glushak/dev/boku/.venv/bin
/Users/Paul_Glushak/.local/share/mise/installs/python/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/pipx/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/poetry/latest/bin
/Users/Paul_Glushak/.local/share/mise/installs/usage/latest/bin
/Users/Paul_Glushak/.local/bin
/opt/homebrew/bin
...
Paul_Glushak@Paul ~/d/boku (main)>
```
---
It looks like the incorrect path value exists in both `$PATH` as well as `$MISE_SHELL`: 
```
MISE_SHELL=fish set -gx __MISE_ORIG_PATH /Users/Paul_Glushak/dev/forter-dev-cli/.venv/bin /Users/Paul_Glushak/.local/share/mise/installs/pipx/latest/bin ...
```

**Comment by jdx** [comment]
this is by design, mise doesn't modify PATH to override things after it was activated to prevent it from aggressively modifying PATH. The [`activate_aggressive`](https://mise.jdx.dev/configuration/settings.html#activate_aggressive) setting modifies this behavior.

**Comment by hxii** [comment]
@jdx am I understanding correctly that the aggressive setting will prepend the new path, while the default should overwrite the old one? If so, the issue is that it’s not being overwritten.
Perhaps I misunderstood?

**Comment by Its-Alex** [comment]
@jdx Hello :wave: Up?

From your point of view, how are we supposed to use the `venv` directory correctly in this case? Because by default a `venv` directory is created but never used :confused:

**Comment by Its-Alex** [comment]
Hello :wave: @syhol

Thanks for your reply, concerning this point:

> If /Users/Paul_Glushak/dev/forter-dev-cli/.venv or /Users/gallegoj/.local/share/virtualenv/gallegoj/bin is not managed by mise, then I would say its not mise's responsibility to deactivate them. Is there a precedent for this behaviour with any other tool? I don't mean to be dismissive, I'm just curious where your expectations come from.

If we use `_.python.venv = ".venv"` mise is supposed to be responsible of this virtual environment no? If no, what is the best way to managed it? If yes why is it not used by default without using `activate_aggressive=true`?

**Comment by jdx** [comment]
I don't think I understand this use-case. It sounds like you've activated a venv after mise, then are wanting mise to override that venv. Why activate the other one at all? I would just use mise for both of them.

mise is careful not to make modifications to PATH that overwrite changes after it was started. Otherwise it would be impossible to do something like `export PATH="somenewpath:$PATH"` because mise would just stomp on top of it. As far as mise is concerned, venv is just modifying env vars like PATH so it's not special. This is the behavior that activate_aggressive disables.

**Comment by syhol** [comment]
mise is actually activating the environment, check `echo $VIRTUAL_ENV` in this situation and you should see the correct directory. jdx explains why the path is not matching your expectation.

However, to your credit, I checked what happens when you have 2 venvs (both **not** managed by mise) and activate them one after the other. The second activation **did** remove the path from the first.

<details>
<summary>uv's venv clobbering old venv paths</summary>

```console
# Code/sandbox/unmanaged-venv
❯ uv venv .venv
Using Python 3.13.0 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate.fish

# Code/sandbox/unmanaged-venv
❯ source .venv/bin/activate.fish

# Code/sandbox/unmanaged-venv via 🐍 v3.13.0 (unmanaged-venv)
❯ echo $PATH | sed 's/ /\n/g'
/Users/simon/Code/sandbox/unmanaged-venv/.venv/bin
/Users/simon/.local/share/mise/installs/node/21.4.0/bin
...

# ~/Code/sandbox/unmanaged-venv via 🐍 v3.13.0 (unmanaged-venv)
❯ mkdir ../unmanaged-venv-2

# ~/Code/sandbox/unmanaged-venv via 🐍 v3.13.0 (unmanaged-venv)
❯ cd ../unmanaged-venv-2/

# Code/sandbox/unmanaged-venv-2 via 🐍 v3.13.0 (unmanaged-venv)
❯ uv venv .venv
Using Python 3.13.0 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate.fish

# Code/sandbox/unmanaged-venv-2 via 🐍 v3.13.0 (unmanaged-venv)
❯ source .venv/bin/activate.fish

# Code/sandbox/unmanaged-venv-2 via 🐍 v3.13.0 (unmanaged-venv-2)
❯ echo $PATH | sed 's/ /\n/g'
/Users/syhol/Code/sandbox/unmanaged-venv-2/.venv/bin
/Users/syhol/.local/share/mise/installs/node/21.4.0/bin
...
```
</details>

@jdx would you be open to matching this behaviour? If you check to see what `.venv/bin/activate.fish` does, it calls the deactivate function before activating the new venv. The deactivate function uses a env var called `$_OLD_VIRTUAL_PATH` to reset the PATH:

<details>
<summary>venv deactivate fish function (runs on activate to clear out the old venv)</summary>

---

Here is the source of the virtualenv version https://github.com/pypa/virtualenv/blob/main/src/virtualenv/activation/fish/activate.fish

and a very similar source for uv:
https://github.com/astral-sh/uv/blob/main/crates/uv-virtualenv/src/activator/activate.fish

```fish
function deactivate -d 'Exit virtualenv mode and return to the normal environment.'
    # reset old environment variables
    if test -n "$_OLD_VIRTUAL_PATH"
        # https://github.com/fish-shell/fish-shell/issues/436 altered PATH handling
        if test (echo $FISH_VERSION | head -c 1) -lt 3
            set -gx PATH (_fishify_path "$_OLD_VIRTUAL_PATH")
        else
            set -gx PATH $_OLD_VIRTUAL_PATH
        end
        set -e _OLD_VIRTUAL_PATH
    end

    if test -n "$_OLD_VIRTUAL_PYTHONHOME"
        set -gx PYTHONHOME "$_OLD_VIRTUAL_PYTHONHOME"
        set -e _OLD_VIRTUAL_PYTHONHOME
    end

    if test -n "$_OLD_FISH_PROMPT_OVERRIDE"
       and functions -q _old_fish_prompt
        # Set an empty local `$fish_function_path` to allow the removal of `fish_prompt` using `functi
ons -e`.
        set -l fish_function_path

        # Erase virtualenv's `fish_prompt` and restore the original.
        functions -e fish_prompt
        functions -c _old_fish_prompt fish_prompt
        functions -e _old_fish_prompt
        set -e _OLD_FISH_PROMPT_OVERRIDE
    end

    set -e VIRTUAL_ENV
    set -e VIRTUAL_ENV_PROMPT

    if test "$argv[1]" != 'nondestructive'
        # Self-destruct!
        functions -e pydoc
        functions -e deactivate
        functions -e _bashify_path
        functions -e _fishify_path
    end
end
```
</details>

I can't see this behaviour in any formal spec but that does seem to be the practical standard for venv activation. Also it is what many (at least 3) people expect to happen. What do you think?

**Comment by jdx** [comment]
I would be, though I don't think we have any mechanism for removing entries from PATH. I don't think that would be simple to achieve.

**Comment by jdx** [comment]
what would probably need to be done is to have a special env var sort of like how we use `MISE_ADD_PATH` called `MISE_RM_PATH` that the plugin gets from here: 

https://github.com/jdx/mise/blob/7ba9eab4d069f430c022f97237564d33ee1e27f5/src/plugins/core/python.rs#L425

however we wouldn't be able to use that in the same place `MISE_ADD_PATH` is consumed I don't think. This logic might need to go into `hook-env` directly to make the removal there. That might be tricky since the logic does a lot of dancing around undoing what mise did. What we might do here is just remove it forever since we won't ever need it again.

That only would solve `mise activate` though. For shims and `mise x` I think this code would need to perform the removal:

    pub fn env_with_path(&self, config: &Config) -> Result<BTreeMap<String, String>> {

**Comment by syhol** [comment]
Are you suggesting you set the old `${VIRTUAL_ENV}/bin` to `MISE_RM_PATH`? It's a bit different from what venv does but it should be a fine solution. Alternatively, could you call `get_pristine_env` while overriding `PATH` with `_OLD_VIRTUAL_PATH`? I'm not sure how that would work with `ToolSet.env` though.

Re: shims and `mise x` - Since env_with_path adds the paths to the start, the new venv path would take precedence anyway. Removing the old venv path would just avoid exposing any extra executables.

> just remove it forever since we won't ever need it again

yeah that should be fine.

**Comment by syhol** [comment]
## Mise activation to mise activation

When mise manages both venvs, I can't recreate this issue at all.

<details>
<summary>Click here to see how I tried to recreate your issue in a docker container</summary>

```console
~/Code/sandbox
❯ docker run --pull=always -it --rm --entrypoint bash jdxcode/mise:latest
latest: Pulling from jdxcode/mise
82312fccb35f: Already exists
4ac722d9cf93: Already exists
261351ed796d: Already exists
a9d319298afc: Already exists
bfd886f8ab4a: Already exists
f41ffa9688c1: Pull complete
aba5a536d181: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:eecc479b6259479ffca5a4f9c68dbfe8631ca62dc59aa60c9ab5e4f6e9982701
Status: Downloaded newer image for jdxcode/mise:latest
root@4ea8237586b4:/mise# eval "$(mise activate bash)"
root@4ea8237586b4:/mise# mkdir -p /srv/proj1 /srv/proj2
root@4ea8237586b4:/mise# echo '[tools]
python = "latest"

[env]
_.python.venv = { path = ".venv", create = true }
'>/srv/proj1/mise.toml
root@4ea8237586b4:/mise# echo "[tools]
poetry = {version='latest', pyproject='pyproject.toml'}
python = '3.10'

[env]
_.python.venv = { path = '.venv', create = true }
">/srv/proj2/mise.toml
root@4ea8237586b4:/mise# mise trust /srv/proj1; mise trust /srv/proj2
mise trusted /srv/proj1
mise trusted /srv/proj2
root@4ea8237586b4:/mise# cd /srv/proj1
mise creating venv with stdlib at: /srv/proj1/.venv
root@4ea8237586b4:/srv/proj1# cd /srv/proj2
mise WARN  no venv found at: /srv/proj2/.venv

To create a virtualenv manually, run:
python -m venv /srv/proj2/.venv
mise WARN  missing: python@3.10.16
mise WARN  no venv found at: /srv/proj2/.venv

To create a virtualenv manually, run:
python -m venv /srv/proj2/.venv
root@4ea8237586b4:/srv/proj2# mise install
mise hint use multiple versions simultaneously with mise use python@3.12 python@3.11
mise hint installing precompiled python from indygreg/python-build-standalone
if you experience issues with this python (e.g.: running poetry), switch to python-build by running mise settings python.compile=1
mise WARN  no venv found at: /srv/proj2/.venv

To create a virtualenv manually, run:
python -m venv /srv/proj2/.venv
mise python@3.10.16 ✓ installed                                                                                                                                                                       mise plugin:poetry ✓ https://github.com/mise-plugins/mise-poetry.git#c285853                                                                                                                          mise poetry@1.8.5 ✓ installed                                                                                                                                                                         mise creating venv with stdlib at: /srv/proj2/.venv
mise-poetry: No pyproject.toml found. Execute `poetry init` to create `/srv/proj2/pyproject.toml` first.
root@4ea8237586b4:/srv/proj2# python --version
Python 3.10.16
root@4ea8237586b4:/srv/proj2# cd ../proj1
root@4ea8237586b4:/srv/proj1# python --version
Python 3.13.1
root@4ea8237586b4:/srv/proj1# cd ../proj2
root@4ea8237586b4:/srv/proj2# python --version
Python 3.10.16
```

</details>

Can you help me reproduce your issue here?

## Manual activation to mise activation

I think this (https://github.com/jdx/mise/issues/2718#issuecomment-2486132494) needs to be implemented to fix this.

But also, come on people, why are you still manually activating your venvs? 😂

**Comment by jdx** [comment]
when I test this it works fine if using aggressive which seems like exactly what it should be used for

**Comment by Its-Alex** [comment]
@syhol I don't manually activate any venvs, this is mise that manage 2 venvs in my case.

**Comment by Its-Alex** [comment]
@syhol Sorry for my very late answer, I made a repository to reproduce the «error», you can find in [here](https://github.com/Its-Alex/mise-sub-python-venv-example)
