### ISSUE TITLE
python virtualenv_default_packages in rtx.toml

### ISSUE THREAD

**Issue by dsully** [jdx/mise#323]
**Describe the bug**
I created a `.rtx.toml` file using the example given in the top level `README.md`:

```
[tools]
python = { version = '3.10', virtualenv = '.venv', virtualenv_default_packages = [
    'jedi',
    'wheel',
] }
```

When I change to that directory, the following error is emitted:

```
Error:
   0: error parsing: /Users/dsully/dev/.../.rtx.toml expected value of "tools.python.default_packages" to be a string, got:  [
          'jedi',
          'wheel',
      ]

Location:
   src/config/mod.rs:403

Version:
   1.23.5 macos-arm64 (built 2023-03-13)
```

**Expected behavior**
The given packages would install with no error. :)

**`rtx doctor` output**

```
$ rtx doctor
rtx version:
  1.23.5 macos-arm64 (built 2023-03-13)

shell:
  /opt/homebrew/bin/fish
  fish, version 3.6.0

rtx environment variables:
  RTX_USE_TOML=1
  RTX_TOOL_OPTS__VENV=.venv
  RTX_SHELL=fish
  RTX_EXPERIMENTAL=1

settings:
  {"experimental": "true", "missing_runtime_behavior": "prompt", "always_keep_download": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:

plugins:
  python   https://github.com/jdxcode/rtx-python.git#5853786

toolset:


No problems found
```

**Comment by jdxcode** [comment]
oh whoops, I documented this but forgot to actually implement it :)

**Comment by jdxcode** [comment]
meanwhile you can use [this](https://github.com/jdxcode/rtx-python#default-python-packages) instead

**Comment by jdxcode** [comment]
I see. In asdf this also only works when installing a python version, but I see how me putting this into `.rtx.toml` implies that different projects can install different packages, which is probably especially useful with virtualenvs.

I can probably do this detection whenever hook-env runs (anytime the prompt is shown), but I'm wondering if it's a mistake to offer this since it appears to be going a lot further than I anticipated. On the other hand, maybe that means it's just more useful than I originally thought?

This is still experimental so I'll probably add the ability to install on hook-env, but I am definitely unsure if this was a good idea or not.

**Comment by jdxcode** [comment]
I suppose another way to phrase what I'm saying is: should it actually be installing from requirements.txt? And if so, is it a good idea for rtx to start dabbling into dependencies instead of just runtime management?

**Comment by dsully** [comment]
I'm not sure - here's my use case: I want to install `jedi` and a few others developer tools for any virtualenv that I need to work in, which may or may not be a repository that I'm a contributor to.

Having that hook available in `rtx` would allow for that instead of a manual step.

At any rate, the current `default packages` functionality at the global config level doesn't make any sense, as it only applies to the install, not the local virtualenv.

**Comment by jdx** [comment]
help my understanding, does using the pipx backend solve this problem? I'm not familiar with why people want packages in their virtualenv. I'm also wondering if maybe uv offers something that would help with this (possibly with the MISE_UV_VENV_AUTO setting)

**Comment by egnor** [comment]
Stepping back a bit?? (Pardon my verbosity!!)

- tool options that affect the central, cached tool install (like "[don't] use precompiled binaries" or "install these packages outside any virtualenv") -- I think we agree those are problematic since they create surprising order dependencies on which tool use request is encountered first (which project you `cd` into first). probably best to minimize these and when they do exist make them part of the effective tool version used to key into the tool install cache (so `python@3.10-precompiled` and `python@3.10-builtfromsource` are effectively separate tool versions).
- BUT, if those installation-tweaking options are set not in a project's `.mise.toml` but in per-user config ("I always want this extra dev tool, even if the project didn't ask for it"), it's not so bad. There are still issues with what happens with existing tool installations when those options are edited, but maybe we assume the user has to deal with that (uninstalling and reinstalling if they care)?
- SEPARATELY (and that's what this bug started out for) there are tool configuration tweaks which only affect the project-local installation. These are things like "create and activate this virtualenv" and "install these packages into that virtualenv". There's no project to project coupling here but there are still subtleties around what happens when the spec changes. Arguably these are all just for convenience, so you can have things happen automatically on first `cd` into a project (or first `mise install` in that project) without having to run `./dev_scripts/setup_for_local_dev.sh` and/or `~/mytweaks/add_my_favorite_fun_tools.sh`?
- BUT in the case of virtualenv creation it is not just a convenience creation, it's also setting environment variables so that virtualenv is activated. There's a bit of trickiness here because if Python virtualenv environment variables are set but the virtualenv isn't created, the Python runtime is sad.

Does that seem right? I haven't looked into pipx or uv but don't think they would change any of this too much?

**Comment by jdx** [comment]
so my question was really about what kind of packages people are installing, are they libraries or CLIs? I think the pipx backend would mitigate this for CLIs because my understanding is you don't need CLIs to be in the venv and probably don't _want_ them in your venv anyways. So `mise use pipx:black` is better than putting it into `virtualenv_default_packages`.

However maybe people have use-cases I don't know about for wanting it in their venv or they want to do it with libraries for some reason—though I don't understand why libraries wouldn't be in pyproject.toml.

> probably best to minimize these and when they do exist make them part of the effective tool version used to key into the tool install cache (so python@3.10-precompiled and python@3.10-builtfromsource are effectively separate tool versions).

this has been raised ever since tool options were introduced and has been a growing concern as we've adopted it for more things. Technically speaking the way this works is that tools have 2 relevant hooks: `install` and `exec_env` (these map to the asdf plugin commands but mise retains the same model even today with backends).

`install` - is only run if the tool is installed, so the tool has no way of changing anything involving tool options because it doesn't even get referenced

`exec_env` - the logic here is more complex because it's cached, and I don't remember the details but effectively it can run be configured to run at least to support `venv`. You can see some of the configuration around this caching [here](https://github.com/mise-plugins/mise-poetry/blob/main/mise.plugin.toml) to get an idea of how it works.

However for core tools like python, exec_env is called every time the prompt is displayed, it's just with plugins where I need to be more judicious about shelling out. tl;dr: it would be possible to do an install but the behavior would be automatically installing when the prompt is displayed, not on a discrete action like `mise install`.

Anyhow, in regards to putting the tool options in the file path—I really dislike that idea. I see those directories as a fundamental part of the DX of using mise, it's something I expect users to interact with, not some implementation detail. We also can't just do something naive like putting the strings in there. Tool options could be something very long like complete shell scripts with several lines. It'd have to be a hash of that, which then means ugly paths like `python@3.10-8fa14cd`.

Not to mention those paths are something so much of the mise codebase relies on that changing it would be a lot of work and bugs. Also, people may not _want_ things to behave that way. What if a tool had an option that only gets run on exec_env but it is 1.2gb—now mise will need separate 1.2gb installs for each of those variants.

Anyhow, that's the state of the world. I don't know what the path forward is. It is a problem that these things are not project scoped. I don't know if it would or should be "fixed".

**Comment by jdx** [comment]
I will note though that you can solve this problem yourself but it does require a fair bit of understanding about how mise works. You could do this:

```toml
[tools]
python = "3.10"
python_with_my_package = {version = "3.10", default_packages="my_package"}
[alias]
python_with_my_package = "core:python"
```

I completely get that this is not ideal in terms of DX.

**Comment by jdx** [comment]
I wonder why I don't just put the alias in the tool:

```toml
[tools]
python = "3.10"
python_with_my_package = {version = "3.10", default_packages="my_package", alias="core:python"}
```

"alias" might be the wrong word there, maybe "backend" or "full"

**Comment by egnor** [comment]
(Setting aside the whole "global tool installation options" issue for this comment, focusing on local customization...)

Use cases for wanting installing things into the virtualenv
- installing actual dependencies of project code, so you can run locally -- typically something like `pip install -r requirements.txt` or `pip install -e .` or similar
- installing dev tools the project officially employs. eg. `pip install black` or `pip install -e '.[dev]'`
- installing dev tools the user particularly likes, eg. `pip install jedi` or `pip install visidata`

Honestly for the first ones I usually end up with SOME extra "set up the local state" step so I pretty much always have a `./dev_scripts/setup_for_local_dev.sh` anyway. (Or, if I'm mise-centric, `mise run setup`.) For example from one of my current projects:

```
[tasks.setup]
run = [
  "git lfs install --local",
  "git lfs pull",
  "mise install",
  "mise x -- arduino-cli core update-index",
#  "mise x -- arduino-cli core install esp32:esp32",
  "mise x -- python3 -m pip install -q --disable-pip-version-check -e .",
]
```

(It would be neat if I didn't have to prefix commands with `mise x` to make sure they pick up the results of `mise install`.)

I was thinking something like, if any task named `postinstall` (or flagged with `autorun = "postinstall"`?) ran automatically after `mise install` (subject to trust settings of course), that could roll project specific setup into `mise install`. And maybe a postinstall task that hadn't been run (or had been modified since running) could be flagged the way a missing runtime is flagged. Also mise could walk up the tree of config files and run all such postinstall tasks, allowing user customizations.

Ideally this might even envelop virtualenv setup, so instead of having special hair on the python tool configuration, you just had your postinstall task create the virtualenv if desired. (But we'd have to deal with the virtualenv activation environment variables and what happens with those before the virtualenv is created.)

**Comment by jdx** [comment]
does [this](https://mise.jdx.dev/hooks.html) work?

**Comment by jdx** [comment]
I wonder if a combination of `hooks.enter` and `hooks.postinstall` would be sufficient here, maybe we would just need to add more to the [cookbook](https://mise.jdx.dev/mise-cookbook.html) so people have some examples to reference

**Comment by egnor** [comment]
Hooks: Oh gosh I never even knew that existed! Was that always there??

Assuming I want to link into the other things about mise tasks, would I just have the hook do "mise run my_postinstall_task"? Do all hooks up the config tree get run? Is there any reason this doesn't completely subsume this request?? I guess just the fact that if runtimes are already installed, people wouldn't run `mise install`, and wouldn't have any prompt to do so??

**Comment by jdx** [comment]
yeah, though if it were me I'd do `mise run -q my_post_install_task` so it doesn't show a bunch of extra output

because this pattern is certainly going to be extremely common I think I should also support this:

```toml
[hooks]
postinstall = { task = "my_postinstall_run" }
```

which would have better performance since mise could directly run the task without needing to launch again—but I haven't done that yet

**Comment by egnor** [comment]
(Or, if you wanted to be gross and magical, shell-split the hook command, and if it starts with "mise run" do the short circuit... :stuck_out_tongue_closed_eyes:)

**Comment by egnor** [comment]
(back to the alias concept for tool customizations)

```
% mise version
2024.11.37 linux-x64 (7ac5ab3 2024-11-30)

% cat .mise.toml
[tools]
python = "3.10"
python_with_my_package = {version = "3.10", default_packages="pyserial"}

[alias]
python_with_my_package = "core:python"

% mise install
mise ERROR python_with_my_package not found in mise tool registry
mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
```

I'm probably missing something?

**Comment by jdx** [comment]
that should work, looks like a bug

**Comment by egnor** [comment]
> that should work, looks like a bug

(Should I open a new bug?)

**Comment by noirbizarre** [comment]
I comment there given my similar issue has been closed. I still link my response to answer the `pipx` approach: https://github.com/jdx/mise/issues/1725#issuecomment-2509886827

I just discovered the hooks too, but this wouldn't work as they are always executed whether you are in a virtualenv or not.

It would work if we had a venv specific hook, but it would still be complicated because depending on the workspace:
- `pip` is present or not
- `uv` might be the package manager

Meaning the just to install few packages (basically dev tools) it would require a complicated script that would introspect the current shell.

I think we share the same use cases, mine being: as a Python dev I always use some tools that I don't want to be added to the project dependencies. Some for convenience (like `iptyhon`, `pudb`), some as requirement IDE requirement (like `debugpy` to enable debugging). They need to be in the virtualenv to work (aka. to access dependencies and to be able to import them and use them like `devtools` debug facilities).

**Comment by jdx** [comment]
Can't you just check if you're in a venv in the hook?

**Comment by noirbizarre** [comment]
I just discovered postinstall hook, and I am going to try ASAP with the different possible case. I'll post feedback there right after 👍🏼 

> [!Note]
> If this works, it is totally enough for me to automatically be to install my tools, and I'll probably do a PR to add it to recipes. Last thing that would make it perfect, the ability to enable virtualenv without having to manually edit the toml. Not necessarily #1726, but maybe being able to write something like `mise set _.python.venv.path .venv && mise set _.python.venv.create true` or some reusable profiles (not environment which are differents) the would enable to write `muse use python@312 --with venv` 🤷‍♂️
> Because as of today working/contributing to a Python project is not straight forward:
>  - set python versioon
>  - edit toml to add `_.python.venv = { path = ".venv", create = true }`
>  - display a prompt to have the venv created
>  - install tools

**Comment by jdx** [comment]
I think you can do this with some of the `mise config` subcommands but I'm not sure

**Comment by egnor** [comment]
Maybe some creative use of `env._.source` ?

**Comment by noirbizarre** [comment]
Hooks don't seem to be executed for be (I filed a separate issue to avoid cluttering more the thread: #3321).

**Comment by syhol** [comment]
> I think you can do this with some of the `mise config` subcommands but I'm not sure

For posterity, `mise config set KEY VALUE` works nicely, e.g.:
```console
❯ mise config set env._.python.venv.path .venv
❯ mise config set env._.python.venv.create true -t bool
❯ mise config set tasks.lint.run "pre-commit run -a"
❯ mise config set hooks.postinstall "pdm sync"
```

**Comment by jdx** [comment]
this thread got a bit long, can someone summarize what gaps are remaining?

**Comment by egnor** [comment]
honestly I'd probably recommend closing out this bug and declaring that the `postinstall` hook should cover it, and then let bugs sprout to cover whatever's missing there (we already have https://github.com/jdx/mise/issues/3313 and https://github.com/jdx/mise/issues/3314)?
