### ISSUE TITLE
Improve npm backend when using multiple NodeJS versions

### ISSUE THREAD

**Issue by hverlin** [jdx/mise#3328]
I am not sure if the `npm` backend current behavior is really useful currently if one is using different Node.JS versions. Given that the `npm` backend is still experimental, it might be a good time to update the current behavior. 

I think `mise` should either:
- indicate which node version to use with the `npm` backend (though which value would be the default?)
- indicate which node version to use for a specific tool installed with the npm backend
- always use the specific node.js version which was used when installing a `npm:<tool>` (in the example below, mise would use `node 22` to run `gitlab-ci-local` even my current project is using `node 18` given that it was installed with `node 22`.
- know that it needs to install a different version of a npm tool for a given backend (probably the easiest option to understand, as it works the same as running `npm i -g <tool>` )

The current behavior only works if a npm package does not depend on a specific Node.js version.

Let's go through an example:
```shell
docker run -it --rm --entrypoint /bin/bash jdxcode/mise
mise self-update -y
cd
mise use -g node@22
mise settings set experimental true
mise use -g npm:gitlab-ci-local
gitlab-ci-local --version # works

mkdir some-project && cd some-project
mise use -e local node@18

gitlab-ci-local --version # fails
mise use -e local npm:gitlab-ci-local # nothing is installed as `mise` re-use the existing package 
gitlab-ci-local --version # also fails as well
# Error: The module '/mise/installs/npm-gitlab-ci-local/4.56.0/lib/node_modules/gitlab-ci-local/node_modules/re2/build/Release/re2.node'
# was compiled against a different Node.js version using
# NODE_MODULE_VERSION 127. This version of Node.js requires
# NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
```

At this point, a user needs to know that they have to force re-install the tool. To get around this, I think the `postinstall` hook seems to be a better solution currently?
```shell
mise config set -f mise.local.toml hooks.postinstall 'npm i -g gitlab-ci-local'
```
However, having a `postinstall` hook in the global configuration is not ideal, so one has to run the command manually instead (and remember to re-run it if upgrading `node` later)

**Comment by jdx** [comment]
this implies there is some mechanism available to tell a node CLI which version of node to use when running it. I don't believe that is possible with node.

**Comment by hverlin** [comment]
`~/.default-npm-packages` will install the list of packages for all Node.js installs, though? It's also global, right?

> this implies there is some mechanism available to tell a node CLI which version of node to use when running it. I don't believe that is possible with node.

I see, it's because it has the following `#!/usr/bin/env node`?
```ts
root@932c4456ab9d:/mise/installs/npm-gitlab-ci-local/4.56/bin# head gitlab-ci-local
#!/usr/bin/env node
import chalk from "chalk";
import yargs from "yargs";
import { Parser } from "./parser.js";
...
```

Maybe `mise` could replace this line with something like:
```shell
#!/usr/bin/env -S mise exec node@22 -- node
```
At least, this seems to work locally. I am not sure if it's a good idea though :thinking: 

Another option: could `mise` track it by installing the package in `/mise/installs/npm-node-22-gitlab-ci-local`? This way it would not load it if the wrong version of node is currently in used?

**Comment by jdx** [comment]
> Maybe mise could replace this line with something like:

we can't change PATH because a CLI may want to use the project's PATH not an overridden one, for example `nodemon`.

> Another option: could mise track it by installing the package in /mise/installs/npm-node-22-gitlab-ci-local

I can't think of any reason this wouldn't work off the top of my head—though I suspect there _are_ reasons that just aren't immediately apparent. It's also quite a bit of work. The resolver doesn't have any way of taking into account what sibling versions are or anything and that logic is already quite complex. Even if this was doable I'm not sure the juice is worth the squeeze.

I think the answer for now is some combination of `~/.default-npm-packages`, `mise -f npm:*`, `devDependencies`, hooks, etc. It's probably best for individuals to decide what works for them rather than mise trying to be intelligent.

Now what I do think could be improved is the `~/.default-npm-packages` interface. It's a relic of asdf past that we use a file for that when everything else we do is inside mise.toml which is where this config should be.

**Comment by jdx** [comment]
I don't think there is anything actionable at the moment here

**Comment by airtonix** [comment]
this line

```
mise use -e local npm:gitlab-ci-local # nothing is installed as `mise` re-use the existing package 
```

should prefer to use locally available described nodejs version over the globally described one.

it's what most people will expect.

**Comment by hverlin** [comment]
I agree that the updating the `PATH` works in most situation (I am using in every node project). However, sometimes, you don't want to add a package in your `package.json`, as everyone will have to install it.

For `gitlab-ci-local`, using `npm i -g gitlab-ci-local` is usually the approach I take, as I don't want everyone + CI to install this package if they don't need it.

I was hoping that `mise` could help a bit here, but it seems that `node` does not provide an easy way for mise to do this

**Comment by jdx** [comment]
It might be possible to do some rewriting of shebangs to point to a certain node version but that itself is tricky since it's unclear which node version it should pin to. It also won't work if the node package uses shim scripts. This also might not be the way node CLIs expect to behave, the CLI may _want_ the `node` on PATH to float to the current one being used and not the one it was installed with.

Practically I think it's ok the way it is. Most node CLIs can run on any recent version of node and don't use native dependencies which would cause it to break between versions.
