### ISSUE TITLE
risk of .rtx.toml in project directory being leaked

### ISSUE THREAD

**Issue by jdx** [jdx/mise#441]
So years ago I once accidentally leaked the aws creds for the Heroku CLI by doing `npm publish` in a directory with a direnv `.envrc` file inside of it, you can actually still see it in the old releases: https://www.npmjs.com/package/heroku-cli/v/6.1.0?activeTab=code

It took months for someone to actually find out this had happened and those creds were out in the open the whole time. It was a disaster and I was embarrassed. However, I think this is something that is likely to happen to a lot of people. At the time, `npm publish` didn't show the files that get packed which made this a lot harder to find.

However my concern isn't npm. My concern is anything that might want to package up an entire directory including dotfiles might also pick up the `.rtx.toml` which may contain sensitive data.

I think the best solution would be if the `.rtx.toml` could be outside of a project directory. However if you had a setup like `~/src/myproj`, then if you put it into `~/src/.rtx.toml` you can't have it be unique per project. I'm wondering if we could use an existing convention here (if anyone knows of one, I don't), or maybe we start one like `~/src/.securedot/myproj/.rtx.toml` or something like that.

What do people think? Of course this would be optional and you could have an `.rtx.toml` file in the project (for non-sensitive data) _and_ one in securedot.

**Comment by dbready** [comment]
I use a monorepo, so that would immediately cause some awkwardness, all projects would inherit the same configuration.

Similarly, I think it is nice if there is a default mechanism to have local overrides that should never be committed to source. Off the cuff suggestion, but if there were a `.rtx.toml` and optional `.rtx_local.toml` file, only the former would be committed. `.rtx.toml` would be the default configuration, but `.rtx_local.toml` would be source control ignored, making it more appropriate for secrets or other user specific configuration? Alternatively, `.rtx.toml` could have a key, similar to `env_path`, which references a supplemental configuration filename that could be stored at an explicit, non-committed location.

**Comment by jdxcode** [comment]
> I use a monorepo, so that would immediately cause some awkwardness, all projects would inherit the same configuration.

No they wouldn't, but my example was bad so it might not have made sense what I was proposing. I wrote `~/src/.securedot/.rtx.toml`, but I meant to put `~/src/.securedot/myproj/.rtx.toml`. The point of this is a centralized directory higher than the project can optionally define rtx.tomls that _don't_ conflict.

I also agree that a `.rtx_local.toml` file makes sense. I was actually thinking about this the other day though was thinking `.local.rtx.toml` to make it behave a bit like DNS. I like what [dotenv-flow](https://www.npmjs.com/package/dotenv-flow) has done here and was thinking we could support something like this (loaded in order, so the lower ones override higher ones):

```
defaults.rtx.toml # intended to be committed to the project
.rtx.toml
.testing.rtx.toml # loaded if RTX_ENV=testing
.production.rtx.toml # loaded if RTX_ENV=production
.local.rtx.toml
.local.testing.rtx.toml # loaded if RTX_ENV=testing
```

**Comment by dbready** [comment]
Default `.rtx.toml` and a standardized local override would be sufficient for my purposes, but I like the optional generic mechanism to pull in a different one if required. However, I am less a fan of the variable loading order depending upon the filename, Would prefer the environment variable always takes priority, something like: `.rtx.toml` -> local override -> `RTX_ENV`.

To engage in a bit of bike-shedding...it would annoy me ever so slightly if the `.rtx.toml` and local override did not get sorted next together (ie `.rtx.toml` and `.local.rtx.toml` are unlikely to be listed next to each other). Obviously, a minor detail, but wanted to mention it.

**Comment by jdxcode** [comment]
> Would prefer the environment variable always takes priority, something like: .rtx.toml -> local override -> RTX_ENV.
I actually just wanted to match dotenv-flow, but it looks like it [works](https://www.npmjs.com/package/dotenv-flow#variables-overwritingpriority) the way you described actually so that's fine.

> it would annoy me ever so slightly if the .rtx.toml and local override did not get sorted next together (ie .rtx.toml and .local.rtx.toml are unlikely to be listed next to each other).

that's actually a good point. `.rtx.local.toml`, `.rtx.production.toml`, `.rtx.production.local.toml` might be better for that reason.

**Comment by dbready** [comment]
Looking more closely at the dotenv-flow priority list, I see what you mean. I do not care for that implicit `.local` override if it matches the `RTX_ENV`, but I can imagine someone benefiting from that use case. I could only hope that the default logging was noisy enough that it would indicate when the `.local` overrides were taking effect, but some could disagree.
