### ISSUE TITLE
consider using rye for python management

### ISSUE THREAD

**Issue by khimaros** [jdx/mise#771]
rye uses best practices and is also implemented in rust:

https://github.com/mitsuhiko/rye

**Comment by jdxcode** [comment]
I don't understand what you're asking for here

**Comment by khimaros** [comment]
rye can be thought of as a combination of poetry for managing package dependencies and asdf-python for maintaining cpython versions.

the benefit of rye is that it allows you to use your virtualenv by simply entering the directory of your project, rather than needing to use `poetry run ...` or `poetry shell` for everything.

the user experience is really ideal and i thought it would be worth having on your radar, if only as an example of a useful project which is covering some of the same niches as rtx.

also, i think there may be ways of combining these two excellent tools.

one option would be to create an rtx plugin which uses rye as an alternative to asdf-python, i'm not sure how compatible this is with the existing rtx shim system.

another option would be to borrow some of the code that rye uses for maintaining its shims to get the aforementioned behavior out of asdf-python or poetry.

yet another would be to add a plugin for [pip-tools])https://github.com/jazzband/pip-tools) to rtx directly, perhaps using some of the code from rye to do so.

or maybe none of these make sense and upon deeper inspection these tools are either philosophically or technically incompatible and this issue can be closed.

**Comment by jdxcode** [comment]
the unfortunate thing is that I'm not really a python developer and python is where rtx needs the most work for sure. I was at one point but that was over a decade ago now.

With my admittedly poor understanding of python workflows though, it seems to me there is an open question around how integrated or separated the runtime management, virtualenv management, and dependency management should be. If my understanding of more modern tools like hatch, pdm, and rye is correct: these are all going for full integration of all 3 (though I might be wrong here, please correct me). If I'm honest I feel like I have this mental block around anything with virtualenvs. The concept should be simple—it's just a directory of dependencies—but I think because I don't use them day-to-day I just don't understand the developer workflows that well.

I think what would be ideal is if I really did a massive deep dive into these products beyond just reading their readmes and actually attempt to develop some sample applications. I think then I'd have a better idea of what an ideal workflow might look like. Whether things should be more tightly integrated directly into rtx (imagine a `rtx python add` command for dependency management, for example), or it should just support things like asdf-{rye,hatch,poetry,pdm} in a better way.

In any case, there is virtualenv management today in rtx. I think one thing I'd like to understand is exactly where that falls short and how rye and other tools are better (I have no doubt they are, I just don't have that understanding yet).

**Comment by khimaros** [comment]
it's possible that i'm using rtx incorrectly for python development, so i'm interested in hearing if there's a well-lit path. here's what i see when using rtx with python naively:

```
$ rtx use python
$ python -c 'import sys; print(sys.path)'
```

shows that all of the paths are "global", meaning that it is not possible to create reproducible environments with rtx alone. this means it's necessary to introduce a secondary tool, such as `pip-tools`, `poetry`, `venv`, `pipenv`, etc.

that's all fine, but all of these tools require some extra interaction by the user to activate the virtual environment, so while rtx switches the cpython version automatically, it is still necessary to manually activate the virtual environment (typically in a subshell) to use the correct per-project libraries.

with rye, the shims are using a shared cpython but the site path seems to be per-project. this means you can simply run 'python fnord.py` and it will be able to import all of the packages installed into the virtualenv of the current project without needing to invoke a subshell.

**Comment by jdxcode** [comment]
there is built-in venv support: https://github.com/jdxcode/rtx/blob/main/docs/python.md#experimental-automatic-virtualenv-creationactivation

**Comment by khimaros** [comment]
that's very helpful. sorry for overlooking that.

the combination of your recommended `.rtx.toml` venv syntax with `pip-tools` works nicely.

```shell
cd <path>
rtx use python@3.11.4
# ... edit the venv= in .rtx.toml ...
pip install pip-tools
# ... add requirements to requirements.in ...
pip-compile
pip-sync
```

from this point, it's only necessary to enter the directory and use use python from $PATH

**Comment by dfang** [comment]
@khimaros rtx can manage python versions like rye which is the biggest selling point of [rye](https://www.playfulpython.com/environment-tools-pdm-poetry-rye/). 

you can [asdf-pdm] to manage `.venv` for you.

see this [link](https://github.com/jdxcode/rtx/issues/634#issuecomment-1635283878)

**Comment by jdxcode** [comment]
yes, just trying to find the time to have a look at what needs to be done for it

**Comment by mustafa0x** [comment]
At least if rtx could use precompiled binaries, as rye does.

> **Note that does mean, that Rye will automatically download and install an appropriate Python binary for you.** These Python binaries are currently pulled from [the indygreg python-build-standalone releases](https://github.com/indygreg/python-build-standalone/releases).

**Comment by andersfylling** [comment]
Just want to throw in my two cents as a professional python dev.

Python can be a little messy imo and it seems to be doing a better job at standardizing the dev environment over time. With that in mind I recommend to keep things simple and not use [Rye](https://github.com/mitsuhiko/rye), not because [Rye](https://github.com/mitsuhiko/rye) is a bad project, but because it's not a good fit. Here's the project description of [Rye](https://github.com/mitsuhiko/rye):
> Rye is [Armin's](https://github.com/mitsuhiko/) personal one-stop-shop for all his Python needs. It installs and manages Python installations, manages pyproject.toml files, installs and uninstalls dependencies, manages virtualenvs behind the scenes. It supports monorepos and global tool installations.
>
> It is a wish of what Python was, with no guarantee to work for anyone else. It's an exploration, and it's far from perfect. Thus also the question: [Should Rye Exist?](https://github.com/mitsuhiko/rye/discussions/6)

A different view is that perhaps something like [mise](https://github.com/jdx/mise) could be used by projects like [Rye](https://github.com/mitsuhiko/rye) and alike. The other way around and you'd be restricting work flows.

---

> @mustafa0x commented 3 weeks ago
> At least if rtx could use precompiled binaries, as rye does.
> 
> > **Note that does mean, that Rye will automatically download and install an appropriate Python binary for you.** These Python binaries are currently pulled from [the indygreg python-build-standalone releases](https://github.com/indygreg/python-build-standalone/releases).

I also agree with this. Having python versions that works well across platforms isn't a obvious benefit most of the time, but you avoid weird headaches when you're actually hit by this. Instead of debugging your system and python, you get to focus on getting stuff done, which I'd imagine is the point of a convenient language like Python.

Using these redistributable python versions is also something I've seen done in Bazel projects for reproducible behavior across platforms. Note that, this should be clarified in documentation as a design decision, if you choose to go down this path. Also see https://gregoryszorc.com/docs/python-build-standalone/main/quirks.html.

**Comment by jdx** [comment]
Standard mise behavior for other language is defaulting to precompiled binaries and compiling if precompiled binaries do not work. That said, I know in general precompiled binaries are not used nearly as much as in say, node. I think I'm leaning towards defaulting to using precompiled binaries (likely under experimental mode at first), and once enough people have used it and like it we could switch to using them by default.

**Comment by mustafa0x** [comment]
`mise install python@latest` on Ubuntu first requires `apt-get install -y zlib1g zlib1g-dev libssl-dev libbz2-dev libsqlite3-dev libffi-dev liblzma-dev libncurses5-dev libreadline-dev`, so precompiled would be a QOL improvement.

**Comment by jdx** [comment]
Reconsidered to do what? There's no clear ask for what exactly rye would fit in
